//#I @"..\Tacs.Core\bin\Debug\netstandard2.0" //need to make a full dotnet build
#load @"..\Tacs.Core\Types.fs"
#load @"..\Tacs.Core\Sequence.fs"
#load @"..\Tacs.Core\FloatOps.fs"
#load @"..\Tacs.Core\IntegerOps.fs"
#load @"..\Tacs.Core\TimeOps.fs"
#load @"..\Tacs.Examples\GoodOrBad.fs"
#load @"..\Tacs.Examples\Complex.fs"
#load @"..\Tacs.Examples\ElapsedTime.fs"
#load @"..\Tacs.Examples\Geospatial\Coordinate2D.fs"
#load @"..\Tacs.Examples\Geospatial\Envelope2D.fs"
#load @"..\Tacs.Examples\Geospatial\Multipoint2D.fs"
#load @"..\Tacs.Examples\Set.fs"
#load @"..\Tacs.Examples\RelativeError.fs"